name: Build Hotspot Launcher

on:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --noconsole tdf_hotspot_launcher.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: TDFHotspotLauncher
          path: dist/tdf_hotspot_launcher.exe
